package nsf.pcvproject;
import gov.nsf.pcv.*;
rule "PCV-00124_CheckProjectDescriptionPageLimitEAGER"
when

	$proposal : Proposal ( 
		$submission : submission != null,
			submission.type == SubmissionType.FULL_PROPOSAL 
			|| == SubmissionType.RENEWAL 
			|| == SubmissionType.RENEWAL_ABR
			|| == SubmissionType.COLLABORATIVE_LEAD,
		$fundingOpportunity : fundingOpportunity != null, 
			fundingOpportunity.fundingOpportunityType == "PD" || == "PA",
		$fundingMechanism : fundingMechanism != null, 
			$fundingMechanism == "EAGER",
		$sectionContent : sectionContent != null,
			sectionContent.projectDescription == SectionContentType.PDF, 
			sectionContent.projectDescriptionPageCount > 8,
		$findings : proposalFindings 
	)
then

	ProposalFinding $proposalFinding = new ProposalFinding();
	$proposalFinding.setFindingCode("PCV-00124");
	$proposalFinding.setFindingLevel(FindingLevel.ERROR);
	$proposalFinding.setMessage("Project Description Exceeds Page Limit - The  Project Description uploaded exceeds the maximum allowable length of 8 pages for an EAGER proposal.");
	insert($proposalFinding );
	$proposal.getProposalFindings().add($proposalFinding);
end

