package nsf.pcvproject;
import gov.nsf.pcv.*;
rule "PCV-00008_CheckEagerProposalDuration"
when
	$proposal : Proposal( 		
		$submission : submission != null,
			submission.type == SubmissionType.FULL_PROPOSAL 
			|| == SubmissionType.RENEWAL 
			|| == SubmissionType.RENEWAL_ABR 
			|| == SubmissionType.COLLABORATIVE_LEAD 
			|| == SubmissionType.COLLABORATIVE_NON_LEAD,
		$fundingOpportunity : fundingOpportunity != null, 
			fundingOpportunity.fundingOpportunityType == "PD" || == "PA", 
		$fundingMechanism : fundingMechanism != null, 
			fundingMechanism == "EAGER", 
		$coverSheet : coversheet != null, 
		coversheet.proposalDurationInMonths > 24,
		$findings : proposalFindings)
then
	
        ProposalFinding $proposalFinding = new ProposalFinding();
        $proposalFinding.setFindingCode("PCV-00008");
        $proposalFinding.setFindingLevel(FindingLevel.WARN);
        $proposalFinding.setMessage("Duration Exceeds 24 months - A duration greater than 24 months has been entered for the Proposal Duration on the \"Remainder of the Cover Sheet\".  The duration of a EAGER proposal cannot exceed 24 months. To correct this warning, please update the duration on the \"Remainder of the Cover Sheet\". ");
	    insert($proposalFinding );
        $proposal.getProposalFindings().add($proposalFinding);
end