package nsf.pcvproject;
import gov.nsf.pcv.*;
rule "PCV-00361_CheckMentoringPlanPageLimit"
when

	$proposal : Proposal ( 
		$fundingOpportunity : fundingOpportunity != null, 
			fundingOpportunity.fundingOpportunityType == "PD" || == "PA",
		$submission : submission != null, 
			submission.type == SubmissionType.FULL_PROPOSAL 
			|| == SubmissionType.RENEWAL 
			|| == SubmissionType.RENEWAL_ABR 
			|| == SubmissionType.COLLABORATIVE_LEAD, 
		$fundingMechanism : fundingMechanism !=null, 
			fundingMechanism == "RAPID" 
			|| == "EAGER" 
			|| == "Conference" 
			|| == "Equipment"
			|| == "International Travel"
			|| == "Research - other than RAPID or EAGER" 
			|| == "Ideas Lab",
		$sectionContent : sectionContent != null,
			sectionContent.postDoctoralMentorinPlanPageCount > 1,
		$findings : proposalFindings 
	)
then

	ProposalFinding $proposalFinding = new ProposalFinding();
	$proposalFinding.setFindingCode("PCV-00361");
	$proposalFinding.setFindingLevel(FindingLevel.ERROR);
	$proposalFinding.setMessage("Mentoring Plan Exceeds Page Limit - The Mentoring Plan uploaded exceeds the maximum allowable length of 1 page." );
	insert($proposalFinding );
	$proposal.getProposalFindings().add($proposalFinding);
end
