package nsf.pcvproject;
import gov.nsf.pcv.*;
rule "PCV-00121_CheckProjectDescriptionRequired"
when
	$proposal : Proposal( 
		$submission : submission != null, 
			submission.type == SubmissionType.FULL_PROPOSAL 
			|| == SubmissionType.RENEWAL 
			|| == SubmissionType.RENEWAL_ABR 
			|| == SubmissionType.COLLABORATIVE_LEAD, 
		$fundingOpportunity : fundingOpportunity != null, 
			fundingOpportunity.fundingOpportunityType == "PD" || == "PA",
		$fundingMechanism: fundingMechanism != null, 
			fundingMechanism == "RAPID" 
			|| == "EAGER" 
			|| == "Conference" 
			|| == "Equipment" 
			|| == "International Travel" 
			|| == "Research - other than RAPID or EAGER" 
			|| == "Ideas Lab",
		sectionContent == null 
			|| sectionContent.projectDescription == null 
			|| sectionContent.projectDescription == SectionContentType.MULTIPLE 
			|| sectionContent.projectDescription == SectionContentType.EMPTY,
		$findings : proposalFindings 
	)
	
then

    ProposalFinding $proposalFinding = new ProposalFinding();
	$proposalFinding.setFindingCode("PCV-00121");
	$proposalFinding.setFindingLevel(FindingLevel.ERROR);
	$proposalFinding.setMessage("No Project Description - A Project Description has not been provided and is required for RAPID, EAGER, Conference, Equipment, International Travel, Research and Ideas Lab types of Funding Mechanisms. To correct this error, please upload a 'Project Description' for this proposal. If submitting a separately submitted collaborative proposal, only the lead institution is required to provide the Project Description.");
	insert($proposalFinding);
	$proposal.getProposalFindings().add($proposalFinding);
end


