package nsf.pcvproject;
import gov.nsf.pcv.*;
rule "PCV-00341_CheckDataManagementPageLimit"
when

	$proposal : Proposal ( 
		$fundingOpportunity : fundingOpportunity != null, 
			fundingOpportunity.fundingOpportunityType == "PD" || == "PA",
		$submission : submission != null, 
			submission.type == SubmissionType.FULL_PROPOSAL 
			|| == SubmissionType.RENEWAL 
			|| == SubmissionType.RENEWAL_ABR 
			|| == SubmissionType.COLLABORATIVE_LEAD, 
		$fundingMechanism : fundingMechanism !=null, 
			fundingMechanism == "RAPID" 
			|| == "EAGER" 
			|| == "Conference" 
			|| == "Equipment"  
			|| == "International Travel" 
			|| == "Research - other than RAPID or EAGER" 
			|| == "Ideas Lab",
		$sectionContent : sectionContent != null,
			sectionContent.dataManagementPlanPageCount > 2,
		$findings : proposalFindings 
	)
then

	ProposalFinding $proposalFinding = new ProposalFinding();
	$proposalFinding.setFindingCode("PCV-00341");
	$proposalFinding.setFindingLevel(FindingLevel.ERROR);
	$proposalFinding.setMessage("Data Management Plan - The Data Management Plan uploaded exceeds the maximum allowable length of 2 pages." );
	insert($proposalFinding );
	$proposal.getProposalFindings().add($proposalFinding);
end
